const jogos = [
    {
        titulo: "The Witcher 3",
        genero: "RPG",
        plataforma: "PC",
        horas_jogadas: 120.5,
        status: "FINALIZADO",
        avaliacao: "10",
        data_inicio: "2024-01-10",
        data_fim: "2024-03-20",
        ano_lancamento: "2015",
    },
    {
        titulo: "Cyberpunk 2077",
        genero: "RPG",
        plataforma: "PC",
        horas_jogadas: 45.0,
        status: "JOGANDO",
        avaliacao: "8",
        data_inicio: "2025-01-05",
        data_fim: "2025-12-31",
        ano_lancamento: "2020",
    },
    {
        titulo: "Hades",
        genero: "Roguelike",
        plataforma: "Nintendo Switch",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-01-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2020,
    },
    {
        titulo: "Celeste",
        genero: "Plataforma",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-03-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2018,
    },
    {
        titulo: "Dark Souls 3",
        genero: "RPG",
        plataforma: "PS4",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-04-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2016,
    },
    {
        titulo: "Stardew Valley",
        genero: "Simulação",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 8,
        data_inicio: "2026-05-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2016,
    },
    {
        titulo: "Hollow Knight",
        genero: "Metroidvania",
        plataforma: "Nintendo Switch",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-06-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2017,
    },
    {
        titulo: "God of War",
        genero: "Ação",
        plataforma: "PS4",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-07-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2018,
    },
    {
        titulo: "Red Dead Redemption 2",
        genero: "Ação",
        plataforma: "PS4",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-08-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2018,
    },
    {
        titulo: "Undertale",
        genero: "RPG",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-09-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2015,
    },
    {
        titulo: "Dead Cells",
        genero: "Roguelike",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-10-01",
        data_fim: "2026-12-31",
        ano_lancamento: 2018,
    },
    {
        titulo: "Sekiro",
        genero: "Ação",
        plataforma: "PS4",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-01-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2019,
    },
    {
        titulo: "Elden Ring",
        genero: "RPG",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-02-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2022,
    },
    {
        titulo: "Disco Elysium",
        genero: "RPG",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-03-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2019,
    },
    {
        titulo: "Cuphead",
        genero: "Plataforma",
        plataforma: "Xbox",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-04-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2017,
    },
    {
        titulo: "Inside",
        genero: "Puzzle",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 8,
        data_inicio: "2026-05-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2016,
    },
    {
        titulo: "Limbo",
        genero: "Puzzle",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 8,
        data_inicio: "2026-06-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2010,
    },
    {
        titulo: "Outer Wilds",
        genero: "Aventura",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-07-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2019,
    },
    {
        titulo: "Subnautica",
        genero: "Sobrevivência",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-08-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2018,
    },
    {
        titulo: "Terraria",
        genero: "Sandbox",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 9,
        data_inicio: "2026-09-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2011,
    },
    {
        titulo: "Minecraft",
        genero: "Sandbox",
        plataforma: "PC",
        horas_jogadas: 0,
        status: "NÃO INICIADO",
        avaliacao: 10,
        data_inicio: "2026-10-10",
        data_fim: "2026-12-31",
        ano_lancamento: 2011,
    }
];

const colecoes = [
    {
        nome: "RPG Favoritos",
        descricao: "Jogos de RPG mais jogados"
    },
    {
        nome: "Indies",
        descricao: "Jogos independentes"
    },
    {
        nome: "Backlog",
        descricao: "Jogos ainda não iniciados"
    }
];

module.exports = {jogos, colecoes}